services:
  web:
    build:
      context: .
      tags:
        - "crm-web:latest"
    ports:
      - 8081:8080
    volumes:
      - .:/golang-docker
    depends_on:
      - database
    container_name: crm-web
    environment:
      - 'DB_USERNAME=root'
      - 'DB_PASSWORD=root'
      - 'DB_HOST=database'
      - 'DB_PORT=3306'
      - 'DB_NAME=mini'
      - 'JWT_SECRET=oPL&Hq4z^5W3i6uX1^nEoA5zee5^k^p2'
      - 'MIGRATE=true'
      - 'SUPER_ADMIN_USERNAME=su_admin'
      - 'SUPER_ADMIN_PASSWORD=su_admin'
      - 'GIN_MODE=release'
  database:
    image: mysql:latest
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=mini'
    container_name: crm-db
    ports:
      - 3333:3306
    volumes:
      - crm-data:/var/lib/mysql



# persisted storage
volumes:
  crm-data: